#!/usr/bin/env python3
# Copyright 2026 Honu Robotics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate every artifact of a X500 loadout from one config file.

Writes into an output directory the URDF, the composed Gazebo model
(model.sdf plus model.config, so the directory works as a model:// root on
GZ_SIM_RESOURCE_PATH) and the ros_gz bridge config, all derived from the
same config through the same generators the build uses. This is what lets a
vehicle be reconfigured without rebuilding, also from a binary install:

    ros2 run x500_gazebo configure_vehicle.py --config my_loadout.yaml --out-dir ~/my_x500
    ros2 launch x500_gazebo sim.launch.xml config_file:=my_loadout.yaml   # does this for you

With --cache the directory is one under $ROS_HOME (default ~/.ros) named
after the config's content, so the same loadout always lands in the same
place and nothing piles up; its path is printed (nothing else), which is
how the launch file calls it.
"""

import argparse
import hashlib
import os
import pathlib
import subprocess
import sys

from ament_index_python.packages import (get_package_prefix,
                                         get_package_share_directory)

MODEL_CONFIG = """\
<?xml version="1.0"?>
<model>
  <name>x500</name>
  <version>1.0</version>
  <sdf version="1.12">model.sdf</sdf>
  <author><name>Honu Robotics</name></author>
  <description>X500, generated by configure_vehicle.py from a loadout config.</description>
</model>
"""


def run(cmd, what):
    out = subprocess.run(cmd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f'{what} failed ({out.returncode}):\n{out.stderr}')
    return out.stdout


def configure(config, out_dir):
    """Generate urdf, model.sdf, model.config and ros_gz_bridge.yaml into out_dir."""
    desc = pathlib.Path(get_package_share_directory('x500_description'))
    gz = pathlib.Path(get_package_share_directory('x500_gazebo'))
    gz_lib = pathlib.Path(get_package_prefix('x500_gazebo')) / 'lib' / 'x500_gazebo'
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    config = pathlib.Path(config).resolve()

    vehicle_xacro = str(desc / 'urdf' / 'x500.urdf.xacro')
    urdf = out_dir / 'x500.urdf'
    urdf.write_text(run(['xacro', vehicle_xacro, f'config_file:={config}'],
                        'URDF generation'))
    sdf = out_dir / 'model.sdf'
    sdf.write_text(run(['xacro', str(gz / 'model.sdf.xacro'),
                        f'config_file:={config}', f'urdf_uri:=file://{urdf}'],
                       'model generation'))
    (out_dir / 'model.config').write_text(MODEL_CONFIG)
    run([sys.executable, str(gz_lib / 'generate_bridge_config.py'),
         str(config), str(urdf), str(out_dir / 'ros_gz_bridge.yaml')],
        'bridge config generation')
    return out_dir


def cache_dir(config):
    """Per loadout directory under $ROS_HOME, keyed by the config's content."""
    ros_home = pathlib.Path(os.environ.get('ROS_HOME', pathlib.Path.home() / '.ros'))
    digest = hashlib.sha256(pathlib.Path(config).read_bytes()).hexdigest()[:12]
    return ros_home / 'x500_gazebo' / digest


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--config', required=True, help='vehicle config yaml')
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument('--out-dir', help='directory to write the artifacts into')
    group.add_argument('--cache', action='store_true',
                       help='write into $ROS_HOME/x500_gazebo/<config hash>, print its path')
    args = ap.parse_args(argv)

    out_dir = cache_dir(args.config) if args.cache else args.out_dir
    configure(args.config, out_dir)
    if args.cache:
        sys.stdout.write(str(out_dir))
    else:
        print(f'wrote x500.urdf, model.sdf, model.config, '
              f'ros_gz_bridge.yaml to {out_dir}')


if __name__ == '__main__':
    main()
