#!/usr/bin/env python3
# Copyright 2026 Honu Robotics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Generate every artifact of a X500 loadout from one config file.

Writes into an output directory the URDF, the composed Gazebo model
(model.sdf plus model.config, so the directory works as a model:// root on
GZ_SIM_RESOURCE_PATH) and the ros_gz bridge config, all derived from the
same config through the same generators the build uses. This is what lets a
vehicle be reconfigured without rebuilding, also from a binary install:

    ros2 run x500_gazebo configure_vehicle.py --config my_loadout.yaml --out-dir ~/my_x500
    ros2 launch x500_gazebo sim.launch.xml config_file:=my_loadout.yaml   # does this for you

With --cache the directory is one under $ROS_HOME (default ~/.ros) named
after the config's content, so the same loadout always lands in the same
place and nothing piles up; its path is printed (nothing else), which is
how the launch file calls it.

--name gives the instance a name of its own: the Gazebo model name and the
topic namespace at once (topic_namespace in the config is overridden), so
several copies of the vehicle can share one world without their topics
colliding. The config that was actually used, with the override applied, is
written next to the artifacts as vehicle.yaml. Without --name the config's
topic_namespace (x500 by default) names the instance, as before.
"""

import argparse
import hashlib
import os
import pathlib
import re
import subprocess
import sys

from ament_index_python.packages import (get_package_prefix,
                                         get_package_share_directory)
import yaml

MODEL_CONFIG = """\
<?xml version="1.0"?>
<model>
  <name>{name}</name>
  <version>1.0</version>
  <sdf version="1.12">model.sdf</sdf>
  <author><name>Honu Robotics</name></author>
  <description>X500, generated by configure_vehicle.py from a loadout config.</description>
</model>
"""


# An instance name is a Gazebo model name, a topic prefix, a ROS namespace
# and a TF prefix at once, so it is held to the strictest of those.
NAME = re.compile(r'^[A-Za-z][A-Za-z0-9_]*$')


def derive(config, name=None):
    """
    Return the effective config text.

    `config` with topic_namespace set to `name` when one is given. Everything
    the generators read comes from this text, so the model name, the plugin
    topics and the bridge agree. It is re-serialized, so the comments of the
    given file do not carry over into vehicle.yaml; the values do.
    """
    if name is not None and not NAME.match(name):
        sys.exit(f'invalid instance name {name!r}: letters, digits and '
                 'underscores, starting with a letter')
    cfg = yaml.safe_load(pathlib.Path(config).read_text()) or {}
    if name:
        cfg['topic_namespace'] = name
    return yaml.safe_dump(cfg, sort_keys=False)


def instance_name(config_text):
    """Return the name an instance goes by: its topic namespace."""
    return (yaml.safe_load(config_text) or {}).get('topic_namespace', 'x500')


def run(cmd, what):
    out = subprocess.run(cmd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f'{what} failed ({out.returncode}):\n{out.stderr}')
    return out.stdout


def configure(config, out_dir, name=None):
    """Generate urdf, model.sdf, model.config and ros_gz_bridge.yaml into out_dir."""
    desc = pathlib.Path(get_package_share_directory('x500_description'))
    gz = pathlib.Path(get_package_share_directory('x500_gazebo'))
    gz_lib = pathlib.Path(get_package_prefix('x500_gazebo')) / 'lib' / 'x500_gazebo'
    out_dir = pathlib.Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    # The config the generators read: the given one with the instance name
    # applied, kept next to the artifacts it produced.
    config_text = derive(config, name)
    config = out_dir / 'vehicle.yaml'
    config.write_text(config_text)

    vehicle_xacro = str(desc / 'urdf' / 'x500.urdf.xacro')
    urdf = out_dir / 'x500.urdf'
    urdf.write_text(run(['xacro', vehicle_xacro, f'config_file:={config}'],
                        'URDF generation'))
    # robot_state_publisher parameter file, so the launch loads the URDF
    # without shelling out to read it (portable: no `cat`).
    (out_dir / 'robot_description.yaml').write_text(yaml.safe_dump(
        {'robot_state_publisher': {'ros__parameters': {
            'robot_description': urdf.read_text()}}}))
    sdf = out_dir / 'model.sdf'
    sdf.write_text(run(['xacro', str(gz / 'model.sdf.xacro'),
                        f'config_file:={config}', f'urdf_uri:=file://{urdf}'],
                       'model generation'))
    (out_dir / 'model.config').write_text(
        MODEL_CONFIG.format(name=instance_name(config_text)))
    run([sys.executable, str(gz_lib / 'generate_bridge_config.py'),
         str(config), str(urdf), str(out_dir / 'ros_gz_bridge.yaml')],
        'bridge config generation')
    return out_dir


def cache_dir(config, name=None):
    """Per instance directory under $ROS_HOME, keyed by the effective config."""
    ros_home = pathlib.Path(os.environ.get('ROS_HOME', pathlib.Path.home() / '.ros'))
    digest = hashlib.sha256(derive(config, name).encode()).hexdigest()[:12]
    return ros_home / 'x500_gazebo' / digest


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--config', required=True, help='vehicle config yaml')
    ap.add_argument('--name', help='instance name: model name and topic namespace '
                                   '(overrides topic_namespace in the config)')
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument('--out-dir', help='directory to write the artifacts into')
    group.add_argument('--cache', action='store_true',
                       help='write into $ROS_HOME/x500_gazebo/<config hash>, print its path')
    args = ap.parse_args(argv)

    out_dir = cache_dir(args.config, args.name) if args.cache else args.out_dir
    configure(args.config, out_dir, args.name)
    if args.cache:
        sys.stdout.write(str(out_dir))
    else:
        print(f'wrote vehicle.yaml, x500.urdf, model.sdf, model.config, '
              f'ros_gz_bridge.yaml, robot_description.yaml to {out_dir}')


if __name__ == '__main__':
    main()
